[.NET] Custom token expiration feature updates
Azure-Samples/communication-services-dotnet-quickstarts pull request #55
Opened 2022-10-06 13:15 UTC by AikoBB

## Purpose

* added the token custom expiration feature

## Does this introduce a breaking change?

```
[ ] Yes
[x] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
*  Get the code
* Take a look at the README.md file under the `AccessTokensQuickstart`

```
git clone [repo-address]
cd [repo-name]
git checkout [branch-name]
npm install
```

* Test the code

```
```

## What to Check
Verify that the following are valid
* verify the tokens expiration time

## Other Information

2022-10-07 12:27 UTC, petrsvihlik requested changes
please apply to other platforms as well

2022-10-07 12:27 UTC, petrsvihlik commented on AccessTokensQuickstart/Program.cs
> +
I'd leave this out

2022-10-07 12:27 UTC, petrsvihlik commented on AccessTokensQuickstart/Program.cs
> +            Console.WriteLine(token);
shorten to show just the important part - expiration

2022-10-10 13:25 UTC, petrsvihlik approved these changes

2022-10-10 16:42 UTC, ddematheu2 approved these changes

2022-10-10 16:43 UTC, merged